version: "3.9"

services:
  api:
    build: ./express-app
  
  react:
    build: ./react-app
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - api